site_name: /r/Roms Megathread
extra_css:
  - css/extra.css
theme:
  name: darkly
nav:
  - Home: index.md
  - Popular: megathread/popular.md
  - Microsoft: megathread/microsoft.md
  - Nintendo: megathread/nintendo.md
  - PC: megathread/pc.md
  - Sega: megathread/sega.md
  - Sony: megathread/sony.md
  - Others: megathread/other.md
